/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ChallengeComponent {
        "header": string;
        "headline": string;
    }
    interface ExampleComponent {
        "exampleProp": string;
    }
}
declare global {
    interface HTMLChallengeComponentElement extends Components.ChallengeComponent, HTMLStencilElement {
    }
    var HTMLChallengeComponentElement: {
        prototype: HTMLChallengeComponentElement;
        new (): HTMLChallengeComponentElement;
    };
    interface HTMLExampleComponentElement extends Components.ExampleComponent, HTMLStencilElement {
    }
    var HTMLExampleComponentElement: {
        prototype: HTMLExampleComponentElement;
        new (): HTMLExampleComponentElement;
    };
    interface HTMLElementTagNameMap {
        "challenge-component": HTMLChallengeComponentElement;
        "example-component": HTMLExampleComponentElement;
    }
}
declare namespace LocalJSX {
    interface ChallengeComponent {
        "header"?: string;
        "headline"?: string;
    }
    interface ExampleComponent {
        "exampleProp"?: string;
    }
    interface IntrinsicElements {
        "challenge-component": ChallengeComponent;
        "example-component": ExampleComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "challenge-component": LocalJSX.ChallengeComponent & JSXBase.HTMLAttributes<HTMLChallengeComponentElement>;
            "example-component": LocalJSX.ExampleComponent & JSXBase.HTMLAttributes<HTMLExampleComponentElement>;
        }
    }
}
